stages:
    - build

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - docker images
        - docker build -t server:$CI_COMMIT_TAG -f server/Dockerfile server
        - docker build -t client:$CI_COMMIT_TAG -f client/Dockerfile client
        - docker images
    tags:
        - gamestore-runner