services:
  mongo:
    image: mongo:8.0

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  server:
    build: ./server

    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - ./server/.env

    depends_on:
      - mongo

volumes:
  mongo-data:
