services:
  mongo:
    image: mongo:8.0

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  server:
    image: $DOCKER_USERNAME/$PROJECT_NAME-server:$IMAGE_TAG

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      MONGO_URI: mongodb://mongo:27017/gamestoredb
      JWT_SECRET: my_secret_jwt_key

    depends_on:
      - mongo

  client:
    image: $DOCKER_USERNAME/$PROJECT_NAME-client:$IMAGE_TAG

    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - server

volumes:
  mongo-data:

